import 'package:flutter/material.dart';

final ColorScheme lightTheme = ColorScheme.fromSeed(
  seedColor: const Color(0xFF006B53),
  brightness: Brightness.light,
  primary: const Color(0xFF006B53),
  primaryContainer: const Color(0xFF77F9D2),
  onPrimaryContainer: const Color(0xFF012018),
  onPrimary: const Color(0xFFFFFFFF),
  secondary: const Color(0xFF4B635A),
  secondaryContainer: const Color(0xFFCEE9DD),
  onSecondaryContainer: const Color(0xFF072019),
  onSecondary: const Color(0xFFFFFFFF),
  tertiary: const Color(0xFF416376),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFC4E8FF),
  onTertiaryContainer: const Color(0xFF001E2C),
  onSurface: const Color(0xFF191C1B),
  surface: const Color(0xFFFBFDFA),
  background: const Color(0xFFFBFBFB),
  onBackground: const Color(0xFF333333),
  error: const Color(0xFFBA1B1B),
  onErrorContainer: const Color(0xFF410001),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFFFDAD4),
  surfaceVariant: const Color(0xFFF0F2FF),
  onSurfaceVariant: const Color(0xFF3F4945),
  outline: const Color(0xFF6F7974),
  inversePrimary: const Color(0xFFF6F7FB),
);
